# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-31 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metEnVente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producteurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(max_length=200, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('photo', models.ImageField(max_length=255, upload_to='C:\\Users\x0crup68962\\Documents\\IMG_20191216_125946.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ref_market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=200)),
                ('heure_deb', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ref_produits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('photo', models.ImageField(max_length=255, upload_to='C:\\Users\x0crup68962\\Documents\\IMG_20191216_125946.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='sinstalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_magasin.ref_market')),
                ('id_producteur', models.ManyToManyField(blank=True, related_name='producteurs', to='client_magasin.Producteurs')),
            ],
        ),
        migrations.AddField(
            model_name='metenvente',
            name='id_producteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_magasin.Producteurs'),
        ),
        migrations.AddField(
            model_name='metenvente',
            name='id_produit',
            field=models.ManyToManyField(blank=True, related_name='produits', to='client_magasin.ref_produits'),
        ),
    ]
