# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-06 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('prenom', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'producteur',
            },
        ),
        migrations.CreateModel(
            name='refMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'refmarket',
            },
        ),
        migrations.CreateModel(
            name='refProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'refproduit',
            },
        ),
        migrations.CreateModel(
            name='sInstalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ManyToManyField(blank=True, related_name='refmarket', to='client_magasin.refMarket')),
                ('producteur', models.ManyToManyField(blank=True, related_name='sinstalleproducteur', to='client_magasin.producteur')),
            ],
            options={
                'db_table': 'sinstalle',
            },
        ),
        migrations.CreateModel(
            name='vend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_magasin.producteur')),
                ('produit', models.ManyToManyField(blank=True, related_name='produit', to='client_magasin.refProduit')),
            ],
            options={
                'db_table': 'vend',
            },
        ),
    ]
