# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metEnVente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metenvente',
            },
        ),
        migrations.CreateModel(
            name='producteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(max_length=200, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('photo', models.ImageField(max_length=255, upload_to='.\\decouvrez_django\\disquaire_project\\client_magasin\\templates\\img\\Koala.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'producteur',
            },
        ),
        migrations.CreateModel(
            name='refMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=200)),
                ('heure_deb', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'refmarket',
            },
        ),
        migrations.CreateModel(
            name='refProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('photo', models.ImageField(max_length=255, upload_to='.\\decouvrez_django\\disquaire_project\\client_magasin\\templates\\img\\Koala.jpg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'produit',
            },
        ),
        migrations.CreateModel(
            name='sInstalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_magasin.refMarket')),
                ('id_producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_magasin.producteur')),
            ],
            options={
                'db_table': 'sinstalle',
            },
        ),
        migrations.AddField(
            model_name='metenvente',
            name='id_producteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_magasin.producteur'),
        ),
        migrations.AddField(
            model_name='metenvente',
            name='id_produit',
            field=models.ManyToManyField(blank=True, related_name='produits', to='client_magasin.refProduit'),
        ),
    ]
