# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-04 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_magasin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='marche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(null=True, verbose_name='référence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('ville', models.CharField(max_length=200, verbose_name='ville')),
                ('picture', models.TextField(verbose_name="URL de l'image")),
                ('producteur', models.ManyToManyField(blank=True, related_name='producteur', to='client_magasin.producteur')),
            ],
            options={
                'verbose_name': 'marche',
                'db_table': 'marche',
            },
        ),
    ]
