# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-06 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_magasin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vend',
            name='imgfile',
            field=models.ImageField(default='a', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
