# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-31 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_magasin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metenvente',
            name='id_producteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_magasin.producteurs'),
        ),
        migrations.AlterField(
            model_name='producteurs',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='C:\\Users\\frup68962\\Documents\\IMG_20191216_125946.jpg'),
        ),
        migrations.AlterField(
            model_name='ref_produits',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='C:\\Users\\frup68962\\Documents\\IMG_20191216_125946.jpg'),
        ),
        migrations.AlterField(
            model_name='sinstalle',
            name='id_producteur',
            field=models.ManyToManyField(blank=True, related_name='producteurs', to='client_magasin.producteurs'),
        ),
    ]
