# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-04 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_magasin', '0002_marche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marche',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='marche',
            name='reference',
        ),
    ]
