# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-06 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_magasin', '0002_vend_imgfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vend',
            name='imgfile',
        ),
        migrations.AddField(
            model_name='refproduit',
            name='imgfile',
            field=models.ImageField(default='null', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
