# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-31 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_magasin', '0002_auto_20200131_1749'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producteurs',
            new_name='producteur',
        ),
        migrations.RenameModel(
            old_name='ref_produits',
            new_name='ref_produit',
        ),
    ]
