# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-04 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_magasin', '0003_auto_20200204_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marche',
            options={'verbose_name': 'marché!!'},
        ),
        migrations.AlterField(
            model_name='producteur',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
