# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-31 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_magasin', '0003_auto_20200131_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ref_market',
            new_name='refMarket',
        ),
        migrations.RenameModel(
            old_name='ref_produit',
            new_name='refProduit',
        ),
    ]
