# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-31 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_magasin', '0004_auto_20200131_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refproduit',
            name='prenom',
        ),
    ]
