# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-11 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='refMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du marché')),
                ('adresse', models.CharField(max_length=200, verbose_name='adresse')),
                ('cp', models.CharField(max_length=5, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=200, verbose_name='Ville')),
                ('latitude', models.DecimalField(blank=True, decimal_places=11, help_text='Coordonnée latitude du marché', max_digits=15, verbose_name='Coordonnée latitude')),
                ('latitlongitudeude', models.DecimalField(blank=True, decimal_places=11, help_text='Coordonnée longitude du marché', max_digits=15, verbose_name='Coordonnée longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'refmarket',
            },
        ),
        migrations.CreateModel(
            name='refPlageHoraire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hDebut', models.TimeField(help_text="Heure d'ouverture du marché", verbose_name="Heure d'ouverture du marché")),
                ('hFin', models.TimeField(help_text='Heure de fermeture du marché', verbose_name='Heure de fermeture du marché')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='Libellé de la tranche horaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'refplagehoraire',
            },
        ),
        migrations.AddField(
            model_name='refmarket',
            name='plageHoraire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.refPlageHoraire'),
        ),
    ]
