# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-11 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refmarket',
            name='latitlongitudeude',
        ),
        migrations.AddField(
            model_name='refmarket',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=11, help_text='Coordonnée longitude du marché', max_digits=15, null=True, verbose_name='Coordonnée longitude'),
        ),
        migrations.AlterField(
            model_name='refmarket',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=11, help_text='Coordonnée latitude du marché', max_digits=15, null=True, verbose_name='Coordonnée latitude'),
        ),
    ]
