# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-11 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_refplagehoraire_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refplagehoraire',
            name='jour',
            field=models.IntegerField(choices=[('Lundi', 1), ('Mardi', 2), ('Mercredi', 3), ('Jeudi', 4), ('Vendredi', 5), ('Samedi', 6), ('Dimanche', 7)], verbose_name='Jours du marché'),
        ),
    ]
