# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-11 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200211_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refplagehoraire',
            name='jour',
            field=models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi')], verbose_name='Jours du marché'),
        ),
    ]
